sonar.exclusions=config/**, tests/**, database/migrations/**, database/seeders/**, resources/views/**, app/Console/Commands/MakeHttpSearch.php, app/Console/Commands/**
sonar.coverage.exclusions=app/Http/Services/Searches/HttpSearch.php, config/**, app/Http/Services/Traits/**, app/Http/helpers.php, app/Exceptions/Handler.php, app/Exceptions/SearchPipelineException.php

